micronaut:
  application:
    name: pixManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/pix-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES
    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
itau:
  contas:
    url: 'http://localhost:9091'
bcb:
  pix:
    url: 'http://localhost:8082'